import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/style/globals.css'
import Header from '@/components/Layout/Header'
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
const inter = Inter({ subsets: ['latin'],weight:['400','500','600','700'] })

export const metadata: Metadata = {
  title: 'Reflect',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Header />
        {children}
      </body>
    </html>
  )
}
